name: geometry_kit
description: A tool kit to work with geometry in Dart and Flutter.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
