name: geometry_kit
description: A set of utils that help with geometry (line, circle, triangle, polygon,...)
version: 0.1.0
homepage: https://github.com/samderlust/geometry_kit

environment:
  sdk: ">=2.17.6 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
